---

- name: Configure login.defs
  lineinfile:
    dest: "/etc/login.defs"
    regexp: '^{{ item.key|upper }}'
    line: '{{ item.key|upper }}\t{{ item.value }}'
  when: item.value
  with_dict: login_defs_options
